CREATE TABLE Tasks (
    id UNIQUEIDENTIFIER PRIMARY KEY,
    title NVARCHAR(255) NOT NULL,
    description NVARCHAR(MAX) NULL,
    bugId UNIQUEIDENTIFIER NOT NULL,
    productId UNIQUEIDENTIFIER NULL,
    productType NVARCHAR(50) NOT NULL,
    status NVARCHAR(50) NOT NULL DEFAULT 'Pending',
    steps NVARCHAR(MAX) NOT NULL,
    currentStepId NVARCHAR(100) NULL,
    createdAt DATETIME NOT NULL,
    updatedAt DATETIME NOT NULL,
    completedAt DATETIME NULL,
    assignedTo NVARCHAR(100) NULL,
    FOREIGN KEY (bugId) REFERENCES Bugs(id)
);
